from typing import Literal
from time import sleep
from keyboard import on_press_key, press, release
import mcpi.minecraft as minecraft
from _classes import Player

game = minecraft.Minecraft.create()

# Set local player as the "admin"
admin: Player = Player(game.getPlayerEntityIds()[0], sword_type="netherite", sword_enchantments={
    "sharpness": 5, "fire_aspect": 2}, is_admin=True)
i = 1

game.player.setting("autojump", False)

view: Literal["1st", "3rd"] = "1st"


def toggle_view(event):
    global view
    global admin
    # BUG
    if view == "1st":
        view = "3rd"
        # Make the camera "follow" the "admin" (local player)
        game.camera.setFollow(admin)
    elif view == "3rd":
        view = "1st"
        game.camera.setNormal(admin)


# Makes sneaking toggle by holding shift when user clicks it once
def sprint(_):
    global sprinting
    if sprinting:
        sprinting = False
        # TODO
    else:
        sprinting = True
        # TODO


def sneak(_):
    if sneaking:
        release("shift")
        sneaking = False
    else:
        press("shift")
        sneaking = True


on_press_key("f5", toggle_view)
on_press_key("shift", sneak)
on_press_key("ctrl", sprint)

game.saveCheckpoint()


if i == 1:
    # If run with pythonw
    try:
        print("Started plugin")  # Only runs on first iteration
    except:
        pass
    game.postToChat('Plugin "making_mcpi_real" activated')

players = []

op: bool = False  # Whether the event was generated by the admin and has op privileges

while True:
    # Recognizing players
    for player in game.getPlayerEntityIds():
        # admin has already been initiated
        if player == admin:
            continue
        players.append(Player(player))

    events = game.events.pollBlockHits()

    # Handles right-clicks w/ sword depending on what is right-clicked
    for event in events:
        if event.entityId == admin.id:
            op = True
        else:
            False
        # Block replacements for "unplaceable" blocks
        if game.getBlock(event.pos) == 46:  # TNT
            game.setBlock(event.pos, 46, 1)  # "Primeable" TNT
        elif game.getBlock(event.pos) == 35 and game.getBlockWithData(event.pos).data == 14:  # Red wool
            game.setBlock(event.pos, 246)  # Glowing Obsidian
        elif game.getBlock(event.pos) == 35 and game.getBlockWithData(event.pos).data == 11 and op:  # Blue Wool
            game.setBlock(event.pos, 8)  # Flowing Water
        elif game.getBlock(event.pos) == 35 and game.getBlockWithData(event.pos).data == 1 and op:  # Orange wool
            game.setBlock(event.pos, 10)  # Flowing Lava
        elif game.getBlock(event.pos) == 49 and op:  # Obsidian
            game.setBlock(event.pos, 7)  # Bedrock
        elif game.getBlock(event.pos) == 20 and op:  # Glass
            game.setBlock(event.pos, 95)  # Invisible Bedrock
        
        # Setting spawnpoint using bed
        elif game.getBlock(event.pos) == 26:
            open("rspnpt.dat", 'w').write(str(event.pos))
            game.postToChat("Respawn point set")
        
        # Save checkpoint
        elif game.getBlock(event.pos) == 47:  # Bookshelf
            game.saveCheckpoint()
            game.postToChat("Restore point set")
        # Restore to last checkpoint
        elif game.getBlock(event.pos) == 247 and (  # Nether Reactor Core
                game.getBlock(event.pos.x - 1, event.pos.y, event.pos.z) == 47  # Bookshelf anywhere around it
                    or game.getBlock(event.pos.x - 1, event.pos.y, event.pos.z) == 47
                    or game.getBlock(event.pos.x + 1, event.pos.y, event.pos.z) == 47
                    or game.getBlock(event.pos.x, event.pos.y, event.pos.z - 1) == 47
                    or game.getBlock(event.pos.x, event.pos.y, event.pos.z + 1) == 47
                    or game.getBlock(event.pos.x, event.pos.y - 1, event.pos.z) == 47
                    or game.getBlock(event.pos.x, event.pos.y + 1, event.pos.z) == 47):
            game.setBlock(event.pos, 247, 1)
            game.restoreCheckpoint()
            game.postToChat("Restoration complete")
        # TODO Chests

        # Prevents lag, VERY slow fps
        sleep(1)
